//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViretTool.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViretTool.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viret Tool.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/W.
        /// </summary>
        public static string BwFilterText {
            get {
                return ResourceManager.GetString("BwFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButtonText {
            get {
                return ResourceManager.GetString("ClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail:.
        /// </summary>
        public static string DetailViewText {
            get {
                return ResourceManager.GetString("DetailViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail view.
        /// </summary>
        public static string DetailWindowTitle {
            get {
                return ResourceManager.GetString("DetailWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; First.
        /// </summary>
        public static string FirstPageButtonText {
            get {
                return ResourceManager.GetString("FirstPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames were submitted..
        /// </summary>
        public static string FramesSentSuccessText {
            get {
                return ResourceManager.GetString("FramesSentSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72.
        /// </summary>
        public static string ImageHeight {
            get {
                return ResourceManager.GetString("ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128.
        /// </summary>
        public static string ImageWidth {
            get {
                return ResourceManager.GetString("ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key word.
        /// </summary>
        public static string KeywordModelName {
            get {
                return ResourceManager.GetString("KeywordModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last &gt;&gt;.
        /// </summary>
        public static string LastPageButtonText {
            get {
                return ResourceManager.GetString("LastPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string MapButtonText {
            get {
                return ResourceManager.GetString("MapButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map is not available - to few frames were returned..
        /// </summary>
        public static string MapNotAvailableText {
            get {
                return ResourceManager.GetString("MapNotAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max frame from shot:.
        /// </summary>
        public static string MaxFromShot {
            get {
                return ResourceManager.GetString("MaxFromShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max frames from video:.
        /// </summary>
        public static string MaxFromVideo {
            get {
                return ResourceManager.GetString("MaxFromVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID:.
        /// </summary>
        public static string MemberIdText {
            get {
                return ResourceManager.GetString("MemberIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string NextPageButtonText {
            get {
                return ResourceManager.GetString("NextPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open database.
        /// </summary>
        public static string OpenDatabaseHeader {
            get {
                return ResourceManager.GetString("OpenDatabaseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Black.
        /// </summary>
        public static string PercentageBlackFilterText {
            get {
                return ResourceManager.GetString("PercentageBlackFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Previous.
        /// </summary>
        public static string PreviousPageButtonText {
            get {
                return ResourceManager.GetString("PreviousPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query is primary.
        /// </summary>
        public static string PrimaryQueryLabel {
            get {
                return ResourceManager.GetString("PrimaryQueryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampled frames:.
        /// </summary>
        public static string SampledFramesText {
            get {
                return ResourceManager.GetString("SampledFramesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results:.
        /// </summary>
        public static string SearchResultsText {
            get {
                return ResourceManager.GetString("SearchResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select directory.
        /// </summary>
        public static string SelectDirectoryText {
            get {
                return ResourceManager.GetString("SelectDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic.
        /// </summary>
        public static string SemanticModelName {
            get {
                return ResourceManager.GetString("SemanticModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string SketchModelName {
            get {
                return ResourceManager.GetString("SketchModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string SortCheckBoxText {
            get {
                return ResourceManager.GetString("SortCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButtonText {
            get {
                return ResourceManager.GetString("SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SubmitButtonTextShort {
            get {
                return ResourceManager.GetString("SubmitButtonTextShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitWindowTitle {
            get {
                return ResourceManager.GetString("SubmitWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team ID:.
        /// </summary>
        public static string TeamIdText {
            get {
                return ResourceManager.GetString("TeamIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name:.
        /// </summary>
        public static string TeamNameText {
            get {
                return ResourceManager.GetString("TeamNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal query 1.
        /// </summary>
        public static string TemporalQuery1Header {
            get {
                return ResourceManager.GetString("TemporalQuery1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal query 2.
        /// </summary>
        public static string TemporalQuery2Header {
            get {
                return ResourceManager.GetString("TemporalQuery2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TestButtonText {
            get {
                return ResourceManager.GetString("TestButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string TestWindowTitle {
            get {
                return ResourceManager.GetString("TestWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string VideoButtonText {
            get {
                return ResourceManager.GetString("VideoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video detail:.
        /// </summary>
        public static string VideoDetailText {
            get {
                return ResourceManager.GetString("VideoDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        public static string WorkingText {
            get {
                return ResourceManager.GetString("WorkingText", resourceCulture);
            }
        }
    }
}
