//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViretTool.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViretTool.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viret Tool.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/W.
        /// </summary>
        public static string BwFilterText {
            get {
                return ResourceManager.GetString("BwFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key word.
        /// </summary>
        public static string KeywordModelName {
            get {
                return ResourceManager.GetString("KeywordModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open database.
        /// </summary>
        public static string OpenDatabaseHeader {
            get {
                return ResourceManager.GetString("OpenDatabaseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Black.
        /// </summary>
        public static string PercentageBlackFilterText {
            get {
                return ResourceManager.GetString("PercentageBlackFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semantic.
        /// </summary>
        public static string SemanticModelName {
            get {
                return ResourceManager.GetString("SemanticModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string SketchModelName {
            get {
                return ResourceManager.GetString("SketchModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal query 1.
        /// </summary>
        public static string TemporalQuery1Header {
            get {
                return ResourceManager.GetString("TemporalQuery1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporal query 2.
        /// </summary>
        public static string TemporalQuery2Header {
            get {
                return ResourceManager.GetString("TemporalQuery2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        public static string WorkingText {
            get {
                return ResourceManager.GetString("WorkingText", resourceCulture);
            }
        }
    }
}
